name: ndwr
favicon: null
layout_spectrum: 0.44738060259260237
typography_spectrum: 0.18278538179583848
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7372513799928129
  lightness: 0.553338073194027
  saturation: 0.7331314389593899
  rhythmicContrast: 0.373964712722227
purpose: []
